#!/usr/bin/env bash

set -e

cd /var/www/

export NVM_DIR="/usr/local/nvm"
. $NVM_DIR/nvm.sh

composer install

nvm use 19.9.0
/usr/local/nvm/versions/node/v19.9.0/bin/npm install && /usr/local/nvm/versions/node/v19.9.0/bin/npm run build

php-fpm
