services:
    nginx:
        image: 'nginx:stable-alpine3.19-perl'
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './docker/nginx/conf.d/:/etc/nginx/conf.d/'
            - './docker/nginx/https/:/etc/nginx/https/'
            - './docker/nginx/logs/:/etc/nginx/logs/'
            - './:/var/www'
        container_name: app_nginx
        depends_on:
            - app
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        volumes:
            - './:/var/www'
        ports:
            - '8000:8000'
        depends_on:
            -   mysql
        container_name: app
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mysql:
        image: 'mysql:8.0'
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - ./tmp:/var/lib/mysql
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
    sail-mysql:
        driver: local
